FROM arm64v8/ros:humble

RUN chmod +x ros_entrypoint.sh

WORKDIR /home/asv_workspace

ENV QT_X11_NO_MITSHM=1
ENV EDITOR=nano
ENV XDG_RUNTIME_DIR=/tmp
ENV ROS_DOMAIN_ID=42


ENV DEBIAN_FRONTEND=noninteractive
# RUN apt-get update && apt-get install -f -y  \
#     cmake \
#     curl \
#     nano \
#     python3-pip \
#     python3-pydantic \
#     ruby-dev \
#     wget \
#     xorg-dev \
#     iputils-ping 

RUN apt-get update && \
    apt-get install -y \
        cmake \
        curl \
        nano \
        python3-pydantic \
        python3-pip && \
    apt-get clean

# RUN apt-get update && \
#     apt-get install -y cmake && \
#     apt-get install -y curl && \
#     apt-get install -y nano && \
#     apt-get install -y python3-pip && \
#     apt-get install -y python3-pydantic && \
#     apt-get install -y ruby-dev && \
#     apt-get install -y wget && \
#     apt-get install -y xorg-dev && \
#     apt-get install -y iputils-ping




# RUN apt install ros-humble-mavros -y
RUN apt-get update && \
    apt-get install -y ros-humble-mavros || true
RUN wget https://raw.githubusercontent.com/mavlink/mavros/ros2/mavros/scripts/install_geographiclib_datasets.sh
RUN chmod +x install_geographiclib_datasets.sh
RUN /bin/bash -c "./install_geographiclib_datasets.sh"

# Download with wget the latest version of geographiclib
RUN pip3 install setuptools==58.2.0

# TODO: Estas dependencias se meteran en un dependencies.txt
RUN pip3 install bluerobotics-ping 
RUN pip3 install "paho-mqtt<2.0.0"
RUN pip3 install pyserial
RUN pip3 install getmac
RUN pip3 install scipy
RUN pip3 install mysql-connector-python

# RUN apt-get autoremove -y \
#     && apt-get clean -y \
#     && rm -rf /var/lib/apt/lists/*

EXPOSE 1883 1880 5688 5678 3306

COPY ../asv_workspace /home/asv_workspace

RUN /bin/bash -c "source /opt/ros/humble/setup.bash; colcon build"
RUN echo 'alias source_ros2="source /opt/ros/humble/setup.bash && source install/setup.bash"' >> .bashrc



COPY /dockerfiles/ros_entrypoint.sh /sbin/ros_entrypoint.sh
RUN sudo chmod 755 /sbin/ros_entrypoint.sh
ENTRYPOINT ["/sbin/ros_entrypoint.sh"]
CMD ["bash"]




